In [9]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.model_selection import KFold 
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import RidgeClassifier
from sklearn.utils.class_weight import compute_class_weight, compute_sample_weight

In [3]:
df = pd.read_csv("human_activity.csv").drop('Unnamed: 0',1)

In [4]:
x = df.drop("label", 1).values
encoder = LabelEncoder()
y = encoder.fit_transform(df["label"])

In [ ]:
y

In [35]:
n_splits = 5 
kf = KFold(n_splits=n_splits)
classifiers = [
        LogisticRegression(),
#        KNeighborsClassifier(3),
         SVC(kernel="linear", C=0.025),
#        SVC(gamma=2, C=1),
         RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
#         MLPClassifier(alpha=1),
#         AdaBoostClassifier(),
         GaussianNB(),
#         QuadraticDiscriminantAnalysis()
    ]
for classifier in classifiers:
    print(classifier)
    total_accuracy = 0 
    for train_index, test_index in kf.split(x):
        y_train, y_test = y[train_index], y[test_index]
        x_train, x_test = x[train_index], x[test_index]
        classifier.fit(x_train, y_train)
        y_pred = classifier.predict(x_test)
        total_accuracy += accuracy_score(y_pred, y_test)
    print(total_accuracy/n_splits)
    
    

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


KeyboardInterrupt: 

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [37]:
X_train

array([[ 0.37661057, -0.01074205, -0.09911139, ..., -0.77468178,
         0.24471351, -0.03634154],
       [ 0.26185921, -0.01852876, -0.11204949, ...,  0.29835121,
        -0.66957885,  0.28713754],
       [ 0.27611906, -0.0141349 , -0.099039  , ..., -0.68966318,
        -0.0387366 , -0.15554466],
       ...,
       [ 0.39825953,  0.01688849, -0.10681026, ..., -0.72614167,
         0.27056857,  0.09757979],
       [ 0.28182212, -0.05014328, -0.11216849, ..., -0.68128907,
         0.30478363,  0.09486393],
       [ 0.27248192, -0.01633501, -0.11623228, ..., -0.89688017,
         0.16361001, -0.01200042]])

In [46]:
level1_train = np.zeros((X_train.shape[0], 12))
level1_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
kf = KFold(n_splits=10)

In [6]:
NUM_LABELS = 6

In [13]:
def get_level_data(X,y,num_labels):
    classifiers = [LogisticRegression(),
            RandomForestClassifier(n_estimators=70, max_depth=5, max_features=0.8, n_jobs=4, class_weight='balanced'),
            BernoulliNB()
        ]
    level1 = np.zeros((X.shape[0], len(classifiers)*num_labels))
    print(level1)
    for tr_idx, te_idx in kf.split(X):
        X_tr, y_tr = X[tr_idx], y[tr_idx]
        X_te, y_te = X[te_idx], y[te_idx]
        for clf_index,clf in enumerate(classifiers):
            print(clf_index)
            clf.fit(X_tr,y_tr)
            predictions = clf.predict_proba(X_te)
            for label_index in range(num_labels):
                current = clf_index*num_labels+label_index
                print(current)
                level1[te_idx,current] = predictions[:,label_index]
    return level1

In [14]:
level1_train = get_level_data(X_train,y_train,NUM_LABELS)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17


In [104]:
level1_train[0]

array([2.08915707e-003, 9.88162597e-001, 9.65080774e-003, 4.33826857e-006,
       5.64368492e-005, 3.66626370e-005, 2.34663251e-001, 6.36608041e-001,
       1.28701008e-001, 1.48045594e-005, 0.00000000e+000, 1.28950709e-005,
       5.80656429e-002, 9.41934357e-001, 1.73062084e-019, 7.57079440e-078,
       6.81658542e-072, 3.89418861e-084, 3.78751817e-097, 1.00000000e+000,
       4.06051531e-109, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [ ]:
level1_test = get_level_data(X_test,y_test,NUM_LABELS)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1
6
7
8
9
10
11
2
12
13
14
15
16
17
0
0
1
2
3
4
5
1


In [ ]:
meta_clf = RidgeClassifier(normalize=True, class_weight='balanced')
meta_clf.fit(level1_train, y_train)
meta_preds = meta_clf.predict(level1_test)
total_accuracy = accuracy_score(meta_preds, y_test)


In [ ]:
total_accuracy

In [ ]:
meta_clf = KNeighborsClassifier(3)
meta_clf.fit(level1_train, y_train)
meta_preds = meta_clf.predict(level1_test)
total_accuracy = accuracy_score(meta_preds, y_test)

In [ ]:
total_accuracy